# Generated by Django 5.2.7 on 2026-01-29 06:02

import app.lessons.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('word_file', models.FileField(upload_to=app.lessons.models.lesson_upload_path)),
                ('presentation_file', models.FileField(upload_to=app.lessons.models.lesson_upload_path)),
                ('video_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to=app.lessons.models.lesson_upload_path)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='subjects.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='lesson_audio/')),
                ('duration', models.PositiveIntegerField(help_text='seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='lessons.lesson')),
            ],
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['subject', 'order'], name='lessons_les_subject_68c0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonaudio',
            index=models.Index(fields=['lesson'], name='lessons_les_lesson__57f24e_idx'),
        ),
    ]
