# Generated by Django 5.2.7 on 2026-01-29 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('game_type', models.CharField(choices=[('quiz', 'Quiz'), ('drag_drop', 'Drag & Drop'), ('true_false', 'True / False')], max_length=50)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('correct_answer', models.JSONField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.game')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['game'], name='games_gamei_game_id_4d39e9_idx')],
            },
        ),
    ]
